import type { KbTopic } from "./references.js";

/**
 * The curated knowledge base.
 *
 * This is the studio's editorial source of truth. It is written and reviewed by
 * a human, it cites retrievable sources, and every claim carries the language
 * it is allowed to be spoken as. The script writer composes *from* these units;
 * it is structurally incapable of inventing a health fact, because the claim
 * list it receives is the only claim list that exists.
 *
 * Adding a topic here is the intended way to extend the catalogue. Live
 * literature (Europe PMC) enriches and corroborates; it never replaces these
 * reviewed units.
 */
export const KB_TOPICS: KbTopic[] = [
  {
    id: "kb_caffeine_brain",
    slug: "caffeine-and-the-brain",
    title: "What caffeine actually does to your brain",
    question: "What happens inside your brain after you drink coffee?",
    category: "brain",
    format: "mechanism",
    keywords: ["caffeine", "adenosine", "adenosine receptor", "sleep pressure", "alertness"],
    visual_score: 0.9,
    educational_score: 0.88,
    shareability: 0.85,
    hooks: [
      { type: "question", text: "What happens in your brain 20 to 45 minutes after coffee?" },
      { type: "counterintuitive", text: "Caffeine does not give you energy. It hides a signal." },
      { type: "surprising_stat", text: "About 95 mg of caffeine in one cup. Here is what it does." },
    ],
    arc: ["hook", "ingest", "absorb", "circulate", "receptor_block", "signal_masked", "clearance", "payoff"],
    cta: "Still up at midnight? Now the timing makes sense.",
    source_card: ["NIH ODS — Caffeine fact sheet", "EFSA — Scientific opinion on the safety of caffeine (2015)", "Guyton & Hall — Textbook of Medical Physiology"],
    claims: [
      {
        id: "cl_caf_1",
        text: "One 240 ml cup of brewed coffee contains roughly 95 mg of caffeine, while a 60 ml espresso contains about 63 mg.",
        level: "government_health_authority",
        sources: ["ods_caffeine", "efsa_caffeine"],
        permitted: ["contains about", "typically provides", "roughly"],
        forbidden: ["always contains", "exactly", "guarantees"],
        numbers: [
          { value: "95", unit: "mg per 240 ml cup", about: true },
          { value: "63", unit: "mg per 60 ml espresso", about: true },
        ],
        components: ["Counter", "BigNumber"],
        visual: "counter",
      },
      {
        id: "cl_caf_2",
        text: "Caffeine is absorbed quickly through the small intestine and reaches the brain within roughly 20 to 45 minutes.",
        level: "narrative_review",
        sources: ["guyton_hall", "ods_caffeine"],
        permitted: ["reaches the brain within roughly", "is absorbed quickly"],
        forbidden: ["instantly", "immediately", "within seconds"],
        numbers: [{ value: "20-45", unit: "minutes to brain", about: true }],
        components: ["Intestine", "BloodVessel", "Brain", "ParticleFlow"],
        visual: "flow",
      },
      {
        id: "cl_caf_3",
        text: "Caffeine occupies adenosine receptors in the brain without activating them, so the rising sleep-pressure signal is blocked rather than reduced.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology"],
        permitted: ["occupies", "blocks the receptor", "competes for"],
        forbidden: ["creates energy", "replaces adenosine", "removes sleep pressure permanently", "cures fatigue"],
        numbers: [],
        caveat: "Caffeine masks the feeling of sleepiness. It does not remove the physiological pressure itself.",
        components: ["Receptor", "Molecule", "Brain", "Signal"],
        visual: "diagram",
      },
      {
        id: "cl_caf_4",
        text: "Because the receptor sites stay occupied, adenosine that is produced anyway accumulates in the brain over the day.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology"],
        permitted: ["accumulates", "builds up"],
        forbidden: ["poisons you", "damages the brain", "floods your brain with toxins"],
        numbers: [],
        components: ["Particle", "Brain", "Pathway"],
        visual: "diagram",
      },
      {
        id: "cl_caf_5",
        text: "About half the caffeine you consume is still in your system five to six hours later, and effects can persist for around 5 to 6 hours.",
        level: "government_health_authority",
        sources: ["ods_caffeine", "efsa_caffeine"],
        permitted: ["about half", "roughly five to six hours", "can persist"],
        forbidden: ["stays in your body forever", "ruins your sleep", "prevents all sleep"],
        numbers: [{ value: "5-6", unit: "hours half-life", about: true }],
        components: ["TimelineTrack", "Counter"],
        visual: "counter",
      },
    ],
  },
  {
    id: "kb_creatine_muscle",
    slug: "creatine-and-muscle-energy",
    title: "What creatine does inside muscle",
    question: "What does creatine actually do inside a muscle cell?",
    category: "supplements",
    format: "supplement",
    keywords: ["creatine", "phosphocreatine", "ATP", "anaerobic", "resynthesis"],
    visual_score: 0.86,
    educational_score: 0.85,
    shareability: 0.8,
    hooks: [
      { type: "question", text: "Where does creatine actually go once you swallow it?" },
      { type: "counterintuitive", text: "Creatine is not a stimulant. It is a battery buffer." },
      { type: "myth_buster", text: "Creatine myth: it does not make you bulky overnight." },
    ],
    arc: ["hook", "ingest", "bloodstream", "uptake", "storage", "reaction", "replenish", "payoff"],
    cta: "Loading is optional: consistent daily intake matters more than a loading protocol.",
    source_card: ["ISSN position stand — creatine safety and efficacy (2017)"],
    claims: [
      {
        id: "cl_crt_1",
        text: "Most people get some creatine from food, especially red meat and fish, and many also take an extra 3 to 5 g per day as a supplement.",
        level: "guideline",
        sources: ["issn_creatine_safety", "guyton_hall"],
        permitted: ["typically", "commonly", "about"],
        forbidden: ["everyone needs", "must take", "is safe for absolutely everyone"],
        numbers: [{ value: "3-5", unit: "g per day", about: true }],
        components: ["Molecule", "Cell", "Membrane"],
        visual: "flow",
      },
      {
        id: "cl_crt_2",
        text: "Absorbed creatine travels in the blood and is taken up by muscle cells through a dedicated transporter.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology"],
        permitted: ["is transported", "is taken up"],
        forbidden: ["teleports", "is absorbed directly into muscle"],
        numbers: [],
        components: ["BloodVessel", "Cell", "Membrane", "ParticleFlow"],
        visual: "flow",
      },
      {
        id: "cl_crt_3",
        text: "Inside the muscle cell most creatine is converted to phosphocreatine, a compound that donates a phosphate group to regenerate ATP during short, intense effort.",
        level: "guideline",
        sources: ["issn_creatine_safety", "boron_medical_physiology"],
        permitted: ["donates a phosphate group", "helps regenerate", "buffers"],
        forbidden: ["creates energy from nothing", "gives you superhuman strength", "replaces training"],
        numbers: [],
        components: ["Muscle", "ATP", "Molecule", "Pathway"],
        visual: "diagram",
      },
      {
        id: "cl_crt_4",
        text: "In muscles that are already saturated, extra creatine usually makes little difference to creatine stores.",
        level: "guideline",
        sources: ["issn_creatine_safety"],
        permitted: ["usually makes little difference", "saturates", "in people who already eat plenty"],
        forbidden: ["more is always better", "everyone must load", "doubles your size"],
        numbers: [],
        caveat: "Effects on training output vary between individuals and depend on diet and training status.",
        components: ["Muscle", "BigNumber", "ComparisonBars"],
        visual: "comparison",
      },
    ],
  },
  {
    id: "kb_protein_digestion",
    slug: "protein-digestion",
    title: "What happens after you eat a high-protein meal",
    question: "What actually happens after you eat 40 grams of protein?",
    category: "nutrition",
    format: "nutrition",
    keywords: ["protein", "pepsin", "stomach", "amino acids", "absorption"],
    visual_score: 0.84,
    educational_score: 0.8,
    shareability: 0.78,
    hooks: [
      { type: "scenario", text: "You just swallowed some protein. Here is what happens in the seconds after." },
      { type: "question", text: "Where does a chicken breast become amino acids?" },
    ],
    arc: ["hook", "mouth", "stomach_acid", "enzyme", "small_intestine", "amino_acids", "blood", "payoff"],
    cta: "Protein is digested mostly as small peptides and amino acids, absorbed in the small intestine.",
    source_card: ["NIH ODS — Protein fact sheet", "Guyton & Hall — Textbook of Medical Physiology"],
    claims: [
      {
        id: "cl_prt_1",
        text: "Swallowed protein reaches the stomach within seconds, where hydrochloric acid unfolds its folded shape.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology"],
        permitted: ["unfolds", "denatures", "begins to be broken down"],
        forbidden: ["dissolves instantly", "is destroyed in seconds"],
        numbers: [],
        components: ["Stomach", "Molecule", "Enzyme"],
        visual: "flow",
      },
      {
        id: "cl_prt_2",
        text: "The enzyme pepsin cuts large protein chains into smaller peptides in the acidic environment of the stomach.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology"],
        permitted: ["cuts into smaller peptides", "begins breaking down"],
        forbidden: ["completes digestion", "absorbs the protein"],
        numbers: [],
        components: ["Stomach", "Enzyme", "Molecule"],
        visual: "diagram",
      },
      {
        id: "cl_prt_3",
        text: "Most amino acid absorption happens in the small intestine, where peptides and amino acids cross the intestinal lining into the blood.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology", "ods_protein"],
        permitted: ["most absorption happens in the small intestine", "cross into the blood"],
        forbidden: ["absorbed in the stomach", "all protein is absorbed at once"],
        numbers: [],
        components: ["Intestine", "Membrane", "BloodVessel", "ParticleFlow"],
        visual: "flow",
      },
      {
        id: "cl_prt_4",
        text: "The liver then redistributes these amino acids, and the kidneys help dispose of any excess.",
        level: "narrative_review",
        sources: ["guyton_hall"],
        permitted: ["redistributes", "helps dispose of excess"],
        forbidden: ["stores protein forever", "turns protein directly into muscle without training"],
        numbers: [],
        components: ["Liver", "Kidney", "BloodVessel"],
        visual: "flow",
      },
    ],
  },
  {
    id: "kb_sleep_appetite",
    slug: "sleep-duration-and-appetite",
    title: "Why short sleep changes appetite signals",
    question: "Why does sleep duration change how hungry you feel?",
    category: "sleep",
    format: "data",
    keywords: ["sleep", "ghrelin", "leptin", "appetite", "insulin sensitivity"],
    visual_score: 0.72,
    educational_score: 0.9,
    shareability: 0.8,
    hooks: [
      { type: "surprising_stat", text: "Two hormones decide how hungry you feel. Sleep moves both." },
      { type: "counterintuitive", text: "Short sleep does not remove hunger. It shifts what your body asks for." },
    ],
    arc: ["hook", "hormone_pair", "short_sleep_change", "chart", "consequence", "payoff"],
    cta: "Adults are generally advised to sleep 7 or more hours per night.",
    source_card: ["CDC — How much sleep adults need", "Guyton & Hall — Textbook of Medical Physiology"],
    claims: [
      {
        id: "cl_slp_1",
        text: "Sleep duration is linked with the hormones that signal hunger and fullness, ghrelin and leptin.",
        level: "narrative_review",
        sources: ["guyton_hall", "cdc_sleep_amount"],
        permitted: ["is linked with", "are involved in", "helps regulate"],
        forbidden: ["causes obesity", "makes you fat", "proves that lack of sleep causes weight gain"],
        numbers: [],
        components: ["Hormone", "Brain", "Signal"],
        visual: "diagram",
      },
      {
        id: "cl_slp_2",
        text: "In laboratory studies of adults, shorter sleep was associated with higher reported hunger and changes in these appetite signals.",
        level: "cohort",
        sources: ["cdc_sleep_amount", "guyton_hall"],
        permitted: ["was associated with", "in laboratory studies", "researchers observed"],
        forbidden: ["proves", "certainly causes", "will make you eat more"],
        numbers: [],
        caveat: "Association is not the same as causation; many factors influence appetite.",
        components: ["ComparisonBars", "Hormone"],
        visual: "chart",
      },
      {
        id: "cl_slp_3",
        text: "Health authorities generally recommend 7 or more hours of sleep per night for adults.",
        level: "government_health_authority",
        sources: ["cdc_sleep_amount"],
        permitted: ["recommend", "generally advise"],
        forbidden: ["you must sleep exactly 8 hours", "anything less is dangerous"],
        numbers: [{ value: "7+", unit: "hours per night", about: false }],
        components: ["Counter", "BigNumber"],
        visual: "counter",
      },
    ],
  },
  {
    id: "kb_glucose_timeline",
    slug: "glucose-after-a-meal",
    title: "What happens to blood glucose after a meal",
    question: "What happens two hours after you eat?",
    category: "metabolism",
    format: "timeline",
    keywords: ["glucose", "insulin", "glycaemic", "postprandial", "beta cell"],
    visual_score: 0.8,
    educational_score: 0.85,
    shareability: 0.75,
    hooks: [
      { type: "timeline_promise", text: "One meal, and the checkpoints that follow it." },
      { type: "question", text: "When exactly does your blood sugar peak after eating?" },
    ],
    arc: ["hook", "t0", "t20", "t45", "t120", "return", "payoff"],
    cta: "The shape of the curve depends on the food, the amount, and the person.",
    source_card: ["Guyton & Hall — Textbook of Medical Physiology", "Boron & Boulpaep — Medical Physiology"],
    claims: [
      {
        id: "cl_glc_1",
        text: "Carbohydrate is digested into glucose, which is absorbed by the small intestine and enters the bloodstream.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology"],
        permitted: ["is absorbed", "enters the bloodstream"],
        forbidden: ["is injected directly into blood", "travels through the lungs"],
        numbers: [],
        components: ["Intestine", "BloodVessel", "Molecule", "Nutrient"],
        visual: "flow",
      },
      {
        id: "cl_glc_2",
        text: "Blood glucose typically rises within about 15 to 30 minutes of starting a carbohydrate-containing meal and usually peaks later in that first hour.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology"],
        permitted: ["typically rises", "usually peaks", "about"],
        forbidden: ["instantly spikes", "always peaks at 30 minutes exactly"],
        numbers: [{ value: "15-30", unit: "minutes to rise", about: true }],
        components: ["LineChart", "Nutrient"],
        visual: "chart",
      },
      {
        id: "cl_glc_3",
        text: "Rising glucose prompts pancreatic beta cells to release insulin, which helps muscle and fat tissue take up glucose.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology"],
        permitted: ["prompts", "helps", "in response to"],
        forbidden: ["forces your pancreas", "cures diabetes", "reverses diabetes"],
        numbers: [],
        components: ["PancreasDiagram", "Hormone", "Membrane", "Receptor"],
        visual: "diagram",
      },
      {
        id: "cl_glc_4",
        text: "For most people glucose then returns toward its usual range within about two hours of eating.",
        level: "narrative_review",
        sources: ["guyton_hall"],
        permitted: ["for most people", "tends to return", "about two hours"],
        forbidden: ["always normalises", "everyone returns to normal", "guaranteed within 2 hours"],
        numbers: [{ value: "2", unit: "hours to return to range", about: true }],
        caveat: "Individual responses vary widely and depend on the meal and the person.",
        components: ["LineChart", "Membrane"],
        visual: "chart",
      },
    ],
  },
  {
    id: "kb_fruit_vs_juice",
    slug: "whole-fruit-vs-fruit-juice",
    title: "Whole fruit versus fruit juice",
    question: "What actually changes when you juice a fruit?",
    category: "nutrition",
    format: "comparison",
    keywords: ["fruit", "juice", "fibre", "glycaemic index", "satiety", "free sugars"],
    visual_score: 0.78,
    educational_score: 0.82,
    shareability: 0.88,
    hooks: [
      { type: "counterintuitive", text: "Whole orange or glass of orange juice: one keeps the structure." },
      { type: "counterintuitive", text: "The sugar is similar. The delivery system is not." },
    ],
    arc: ["hook", "whole_side", "juice_side", "fibre_removed", "texture_signal", "guidance", "payoff"],
    cta: "WHO recommends keeping free sugars below 10 percent of daily energy intake.",
    source_card: ["WHO — Healthy diet fact sheet", "EFSA — Dietary reference values for sugars (2010)"],
    claims: [
      {
        id: "cl_frt_1",
        text: "Whole fruit keeps its fibrous structure, which slows how quickly its sugars are released and digested.",
        level: "guideline",
        sources: ["efsa_fibre", "who_healthy_diet"],
        permitted: ["tends to slow", "is associated with a slower", "fibre slows digestion"],
        forbidden: ["juice has zero nutrition", "fruit sugar is poison", "prevents diabetes entirely"],
        numbers: [],
        components: ["Cell", "Membrane", "Nutrient", "Intestine"],
        visual: "diagram",
      },
      {
        id: "cl_frt_2",
        text: "Juicing removes much of that fibre and changes the texture and volume of what you consume.",
        level: "guideline",
        sources: ["efsa_fibre", "efsa_sugars"],
        permitted: ["removes much of the fibre", "changes texture"],
        forbidden: ["strips all nutrients", "is poison"],
        numbers: [],
        components: ["ComparisonBars", "Molecule"],
        visual: "comparison",
      },
      {
        id: "cl_frt_3",
        text: "Because juice is usually drunk faster and in less volume, the same amount of sugar is often consumed over a shorter time.",
        level: "guideline",
        sources: ["efsa_sugars", "who_healthy_diet"],
        permitted: ["often", "usually", "tends to be"],
        forbidden: ["always spikes blood sugar", "is equivalent to candy", "causes diabetes"],
        numbers: [],
        components: ["LineChart", "Nutrient"],
        visual: "chart",
      },
      {
        id: "cl_frt_4",
        text: "WHO recommends keeping free sugars below 10 percent of total daily energy intake, and notes that 5 percent or less offers additional benefit.",
        level: "guideline",
        sources: ["who_healthy_diet", "efsa_sugars"],
        permitted: ["recommends", "suggests"],
        forbidden: ["you must cut all sugar", "fruit is dangerous"],
        numbers: [{ value: "10", unit: "% energy from free sugars", about: false }],
        components: ["PercentageRing", "Counter"],
        visual: "counter",
      },
    ],
  },
  {
    id: "kb_water_after_eating",
    slug: "water-after-eating-indigestion",
    title: "Does drinking water after eating cause indigestion?",
    question: "Does drinking water after eating cause indigestion?",
    category: "myths",
    format: "myth",
    keywords: ["water", "digestion", "gastric emptying", "indigestion", "sipping"],
    visual_score: 0.7,
    educational_score: 0.86,
    shareability: 0.9,
    hooks: [
      { type: "myth_buster", text: "MYTH: water after food causes indigestion." },
      { type: "question", text: "Does a glass of water ruin your meal?" },
    ],
    arc: ["hook", "myth_card", "what_stomach_does", "evidence", "what_to_watch", "payoff"],
    cta: "Total water intake over a day matters more than the exact timing.",
    source_card: ["NHS — Indigestion", "EFSA — Dietary reference values for water (2010)"],
    claims: [
      {
        id: "cl_wat_1",
        text: "The stomach already secretes its own fluid, and gastric emptying is a controlled process rather than something a glass of water stops.",
        level: "narrative_review",
        sources: ["guyton_hall", "nhs_digestion_indigestion"],
        permitted: ["is a controlled process", "is not stopped by"],
        forbidden: ["proves the myth false forever", "water can never affect digestion"],
        numbers: [],
        components: ["Stomach", "Membrane", "Signal"],
        visual: "diagram",
      },
      {
        id: "cl_wat_2",
        text: "Indigestion is commonly reported after large, rich or fast meals, and it usually involves symptoms such as bloating, pain or reflux.",
        level: "narrative_review",
        sources: ["nhs_digestion_indigestion", "niddk_digestive"],
        permitted: ["is commonly reported after", "often involves"],
        forbidden: ["is always caused by", "only happens because of"],
        numbers: [],
        components: ["Stomach", "KeyValueList", "StatTile"],
        visual: "diagram",
      },
      {
        id: "cl_wat_3",
        text: "For most adults, how much fluid is taken in across a day matters more than the exact moment it is drunk.",
        level: "guideline",
        sources: ["efsa_water"],
        permitted: ["matters more than", "for most adults", "authorities advise"],
        forbidden: ["proves the myth is nonsense", "no evidence exists"],
        caveat: "People with heart or kidney conditions may be advised differently by their clinician.",
        numbers: [],
        components: ["Counter", "TimelineTrack"],
        visual: "counter",
      },
    ],
  },
  {
    id: "kb_glucose_journey",
    slug: "one-glucose-molecule",
    title: "Follow one glucose molecule to a muscle",
    question: "Follow one glucose molecule from food to a working muscle.",
    category: "metabolism",
    format: "system-journey",
    keywords: ["glucose", "absorption", "portal vein", "insulin", "GLUT4", "muscle"],
    visual_score: 0.95,
    educational_score: 0.92,
    shareability: 0.8,
    hooks: [
      { type: "scenario", text: "One glucose molecule. Let's follow it all the way in." },
      { type: "question", text: "How does a sugar cube become muscle fuel?" },
    ],
    arc: ["hook", "mouth", "stomach", "small_intestine", "portal_blood", "pancreas", "muscle_cell", "glycogen", "payoff"],
    cta: "Insulin is the signal that opens the door into the muscle cell.",
    source_card: ["Guyton & Hall — Textbook of Medical Physiology", "Boron & Boulpaep — Medical Physiology"],
    claims: [
      {
        id: "cl_gjr_1",
        text: "The journey starts in the small intestine, where glucose is absorbed across the intestinal lining into blood vessels.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology"],
        permitted: ["is absorbed across", "enters blood vessels"],
        forbidden: ["passes through the stomach wall directly"],
        numbers: [],
        components: ["Intestine", "Membrane", "BloodVessel", "Nutrient"],
        visual: "flow",
      },
      {
        id: "cl_gjr_2",
        text: "From the intestine the blood carries glucose to the liver, which stores part of it as glycogen and releases the rest to keep blood glucose steady.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology"],
        permitted: ["stores part of it as glycogen", "releases the rest"],
        forbidden: ["the liver filters toxins from sugar", "converts sugar into energy instantly"],
        numbers: [],
        components: ["Liver", "Pathway", "Molecule", "BloodVessel"],
        visual: "flow",
      },
      {
        id: "cl_gjr_3",
        text: "When blood glucose rises, insulin helps muscle cells take up glucose by moving transporters to the cell membrane.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology"],
        permitted: ["helps muscle cells take up", "moves transporters to the membrane"],
        forbidden: ["insulin opens every cell", "cures diabetes", "forces glucose in"],
        numbers: [],
        components: ["Muscle", "Membrane", "Receptor", "Hormone", "Pathway"],
        visual: "diagram",
      },
      {
        id: "cl_gjr_4",
        text: "Inside the muscle, glucose can be stored as glycogen or used to help rebuild ATP during contraction.",
        level: "narrative_review",
        sources: ["boron_medical_physiology", "who_physical_activity"],
        permitted: ["can be stored as", "is used to help rebuild"],
        forbidden: ["is instantly burned as pure energy", "becomes muscle in one session"],
        numbers: [],
        components: ["Muscle", "ATP", "Pathway", "Molecule"],
        visual: "diagram",
      },
    ],
  },
  {
    id: "kb_eggs_timeline",
    slug: "eggs-two-hours-later",
    title: "What happens after you eat eggs",
    question: "What happens two hours after eating eggs?",
    category: "nutrition",
    format: "timeline",
    keywords: ["eggs", "protein", "fat", "cholecystokinin", "amino acids"],
    visual_score: 0.75,
    educational_score: 0.78,
    shareability: 0.82,
    hooks: [
      { type: "timeline_promise", text: "Two eggs, four checkpoints, four hours." },
      { type: "question", text: "What is actually happening two hours after breakfast?" },
    ],
    arc: ["hook", "t0", "t30", "t90", "t120", "t240", "payoff"],
    cta: "Protein-rich meals keep digestive signals active for several hours.",
    source_card: ["NIH ODS — Protein fact sheet", "Guyton & Hall — Textbook of Medical Physiology"],
    claims: [
      {
        id: "cl_egg_1",
        text: "Egg protein is digested in the stomach and small intestine into small peptides and amino acids.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology", "ods_protein"],
        permitted: ["is digested into", "is broken down into"],
        forbidden: ["is absorbed whole", "remains intact in the blood"],
        numbers: [],
        components: ["Stomach", "Intestine", "Enzyme"],
        visual: "flow",
      },
      {
        id: "cl_egg_2",
        text: "Fat in the egg slows gastric emptying, so the meal leaves the stomach more gradually than a carbohydrate-only meal.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology"],
        permitted: ["slows gastric emptying", "leaves the stomach more gradually"],
        forbidden: ["blocks digestion completely", "spoils your metabolism"],
        numbers: [],
        components: ["Stomach", "TimelineTrack"],
        visual: "flow",
      },
      {
        id: "cl_egg_3",
        text: "Amino acids from the meal appear in the blood well before two hours, and are then used or stored according to need.",
        level: "narrative_review",
        sources: ["guyton_hall", "issn_protein_position"],
        permitted: ["appear in the blood", "are used or stored according to need"],
        forbidden: ["all of it becomes muscle", "the body stores unlimited protein"],
        numbers: [],
        caveat: "Muscle protein synthesis response depends on total intake and training status.",
        components: ["BloodVessel", "Muscle", "Pathway"],
        visual: "flow",
      },
    ],
  },
  {
    id: "kb_hydration",
    slug: "hydration-physiology",
    title: "How the body regulates water",
    question: "What happens when you drink a glass of water?",
    category: "hydration",
    format: "mechanism",
    keywords: ["water", "osmolality", "ADH", "thirst", "kidney", "sweat"],
    visual_score: 0.82,
    educational_score: 0.84,
    shareability: 0.76,
    hooks: [
      { type: "question", text: "What does a glass of water trigger in the body?" },
      { type: "counterintuitive", text: "Your kidneys set the water limit, not your willpower." },
    ],
    arc: ["hook", "ingest", "absorb", "blood_osmolality", "thirst_signal", "hypothalamus", "kidney", "payoff"],
    cta: "EFSA set adequate total water intake at about 2.5 litres per day for adult men.",
    source_card: ["EFSA — Dietary reference values for water (2010)", "Guyton & Hall — Textbook of Medical Physiology"],
    claims: [
      {
        id: "cl_hyd_1",
        text: "Water is absorbed across the gut lining and joins the blood within minutes of being drunk.",
        level: "guideline",
        sources: ["efsa_water", "guyton_hall"],
        permitted: ["is absorbed", "within minutes"],
        forbidden: ["goes straight to the kidneys", "is instantly in your cells"],
        numbers: [],
        components: ["Intestine", "BloodVessel", "Molecule", "ParticleFlow"],
        visual: "flow",
      },
      {
        id: "cl_hyd_2",
        text: "The hypothalamus senses the concentration of dissolved particles in the blood and drives thirst when it rises.",
        level: "narrative_review",
        sources: ["guyton_hall", "boron_medical_physiology"],
        permitted: ["senses", "drives thirst when it rises", "regulates"],
        forbidden: ["reads your mind", "can detect any amount of water in the body"],
        numbers: [],
        components: ["Brain", "Signal", "Receptor", "Molecule"],
        visual: "diagram",
      },
      {
        id: "cl_hyd_3",
        text: "The kidneys adjust how much water is reabsorbed, and sweat is a major route of water loss that varies with heat and activity.",
        level: "guideline",
        sources: ["efsa_water", "boron_medical_physiology"],
        permitted: ["adjust how much water is reabsorbed", "is a major route of water loss"],
        forbidden: ["sweat is only salt", "sweat is pure toxin"],
        numbers: [],
        components: ["Kidney", "Pathway", "ParticleFlow"],
        visual: "diagram",
      },
      {
        id: "cl_hyd_4",
        text: "EFSA set an adequate intake for total water of about 2.5 litres per day for adult men and 2 litres for adult women, including food and other drinks.",
        level: "guideline",
        sources: ["efsa_water"],
        permitted: ["set an adequate intake", "about", "including food and other drinks"],
        forbidden: ["you must drink exactly 2.5 litres", "more water is always better"],
        numbers: [{ value: "2.5", unit: "litres per day, men", about: true }],
        components: ["Counter", "BigNumber", "StatTile"],
        visual: "counter",
      },
    ],
  },
  {
    id: "kb_heart_exercise",
    slug: "heart-response-to-exercise",
    title: "How the heart responds to exercise",
    question: "What does the heart do differently during exercise?",
    category: "cardio",
    format: "data",
    keywords: ["heart", "stroke volume", "cardiac output", "sympathetic", "oxygen"],
    visual_score: 0.8,
    educational_score: 0.83,
    shareability: 0.74,
    hooks: [
      { type: "counterintuitive", text: "Your heart does not beat faster because it is working harder. It beats more volume." },
      { type: "question", text: "What actually changes in the heart when you run?" },
    ],
    arc: ["hook", "resting_state", "signal", "rate_up", "volume_up", "chart", "cool_down", "payoff"],
    cta: "Cardiac output is the product of heart rate and stroke volume.",
    source_card: ["WHO — Physical activity fact sheet", "Boron & Boulpaep — Medical Physiology"],
    claims: [
      {
        id: "cl_hrt_1",
        text: "At rest the heart moves roughly five litres of blood per minute, and that figure rises several-fold during exercise.",
        level: "narrative_review",
        sources: ["boron_medical_physiology", "who_physical_activity"],
        permitted: ["roughly", "rises several-fold", "at rest"],
        forbidden: ["exactly", "always triples"],
        numbers: [{ value: "5", unit: "litres per minute at rest", about: true }],
        components: ["Heart", "BigNumber", "StatTile"],
        visual: "counter",
      },
      {
        id: "cl_hrt_2",
        text: "Sympathetic stimulation increases heart rate and contractility, so each beat ejects more blood.",
        level: "narrative_review",
        sources: ["boron_medical_physiology", "guyton_hall"],
        permitted: ["increases", "so each beat ejects more blood"],
        forbidden: ["damages the heart", "overloads a healthy heart"],
        numbers: [],
        components: ["Heart", "Signal", "BloodVessel", "Neurotransmitter"],
        visual: "diagram",
      },
      {
        id: "cl_hrt_3",
        text: "Muscle arterioles widen during activity so more blood reaches the working tissue.",
        level: "narrative_review",
        sources: ["boron_medical_physiology"],
        permitted: ["widen", "so more blood reaches"],
        forbidden: ["blood rushes to muscles instantly at the first step"],
        numbers: [],
        components: ["Muscle", "BloodVessel", "ParticleFlow"],
        visual: "flow",
      },
      {
        id: "cl_hrt_4",
        text: "Cardiac output is calculated as heart rate multiplied by stroke volume.",
        level: "narrative_review",
        sources: ["boron_medical_physiology"],
        permitted: ["is calculated as", "is the product of"],
        forbidden: ["is unrelated to heart rate"],
        numbers: [],
        components: ["Counter", "KeyValueList"],
        visual: "counter",
      },
    ],
  },
  {
    id: "kb_fibre_digestion",
    slug: "fibre-and-digestion",
    title: "What fibre does in the gut",
    question: "What does dietary fibre actually do in the gut?",
    category: "digestion",
    format: "nutrition",
    keywords: ["fibre", "gut", "viscosity", "fermentation", "short chain fatty acids", "transit"],
    visual_score: 0.76,
    educational_score: 0.84,
    shareability: 0.7,
    hooks: [
      { type: "question", text: "What does fibre do that calories cannot?" },
      { type: "counterintuitive", text: "Fibre is not one thing, and it does not all work the same way." },
    ],
    arc: ["hook", "reach_intestine", "two_families", "viscosity", "fermentation", "payoff"],
    cta: "EFSA set an adequate fibre intake of about 25 g per day for adults.",
    source_card: ["EFSA — Dietary reference values for fibre (2010)", "WHO — Healthy diet fact sheet"],
    claims: [
      {
        id: "cl_fbr_1",
        text: "Fibre reaches the large intestine largely undigested, because human enzymes do not break most of it down.",
        level: "guideline",
        sources: ["efsa_fibre", "guyton_hall"],
        permitted: ["largely undigested", "do not break most of it down"],
        forbidden: ["provides calories", "is fully digested"],
        numbers: [],
        components: ["Intestine", "Molecule", "Pathway"],
        visual: "flow",
      },
      {
        id: "cl_fbr_2",
        text: "Some fibre forms hold water and increase the viscosity of intestinal contents, which can slow how quickly nutrients are absorbed.",
        level: "guideline",
        sources: ["efsa_fibre"],
        permitted: ["can slow", "increase viscosity", "some forms"],
        forbidden: ["blocks all absorption", "prevents any sugar entering blood"],
        numbers: [],
        components: ["Intestine", "Membrane", "Molecule"],
        visual: "diagram",
      },
      {
        id: "cl_fbr_3",
        text: "Other fibre types are fermented by gut bacteria, producing short-chain fatty acids that the colon uses as fuel.",
        level: "guideline",
        sources: ["efsa_fibre", "who_healthy_diet"],
        permitted: ["are fermented by gut bacteria", "producing short-chain fatty acids"],
        forbidden: ["feeds bacteria that cure disease", "cleanses the gut completely"],
        numbers: [],
        components: ["Cell", "Pathway", "Particle", "Molecule"],
        visual: "diagram",
      },
      {
        id: "cl_fbr_4",
        text: "EFSA set an adequate intake of about 25 g of fibre per day for adults.",
        level: "guideline",
        sources: ["efsa_fibre"],
        permitted: ["set an adequate intake", "about"],
        forbidden: ["you must eat exactly 25 g", "more is always better"],
        numbers: [{ value: "25", unit: "g per day", about: true }],
        components: ["Counter", "BigNumber"],
        visual: "counter",
      },
    ],
  },
  {
    id: "kb_exercise_muscle",
    slug: "what-happens-during-exercise",
    title: "What happens to muscle during exercise",
    question: "What actually happens inside muscle during a hard set?",
    category: "exercise",
    format: "mechanism",
    keywords: ["muscle", "ATP", "fibre types", "motor unit", "saturation", "oxygen"],
    visual_score: 0.88,
    educational_score: 0.82,
    shareability: 0.72,
    hooks: [
      { type: "question", text: "What runs out when muscle gets that burning feeling?" },
      { type: "counterintuitive", text: "The burn is not the same thing as damage." },
    ],
    arc: ["hook", "signal", "motor_unit", "atp_demand", "oxygen_supply", "accumulation", "adaptation", "payoff"],
    cta: "Training adaptation comes from repeated stress and recovery, not from one hard session.",
    source_card: ["WHO — Physical activity fact sheet", "Boron & Boulpaep — Medical Physiology"],
    claims: [
      {
        id: "cl_exr_1",
        text: "A nerve signal arrives at the muscle and triggers calcium release inside the fibre, which starts contraction.",
        level: "narrative_review",
        sources: ["boron_medical_physiology", "guyton_hall"],
        permitted: ["triggers", "starts contraction", "arrives at"],
        forbidden: ["telegraphs the muscle instantly from the brain without delay"],
        numbers: [],
        components: ["Muscle", "Neuron", "Signal", "Receptor"],
        visual: "diagram",
      },
      {
        id: "cl_exr_2",
        text: "Muscle contraction needs ATP, and as effort rises more of that ATP has to be made within each second.",
        level: "narrative_review",
        sources: ["boron_medical_physiology"],
        permitted: ["needs ATP", "as effort rises", "within each second"],
        forbidden: ["ATP runs out completely", "you have a fixed ATP tank that empties"],
        numbers: [],
        components: ["Muscle", "ATP", "Molecule"],
        visual: "diagram",
      },
      {
        id: "cl_exr_3",
        text: "When demand outpaces what oxygen can supply, the fibre leans more on faster pathways that do not need oxygen directly.",
        level: "narrative_review",
        sources: ["boron_medical_physiology"],
        permitted: ["when demand outpaces", "leans more on", "do not need oxygen directly"],
        forbidden: ["causes lactic acid buildup permanently", "is caused by lack of oxygen alone"],
        numbers: [],
        caveat: "The 'lactic acid' explanation of muscle burn is outdated; hydrogen ions rise as pH falls.",
        components: ["Muscle", "Pathway", "BloodVessel", "Particle"],
        visual: "flow",
      },
      {
        id: "cl_exr_4",
        text: "Repeated training followed by recovery is what builds capacity, rather than any single session.",
        level: "guideline",
        sources: ["who_physical_activity"],
        permitted: ["repeated training", "followed by recovery", "builds capacity"],
        forbidden: ["one session transforms your body", "train through injury to adapt faster"],
        numbers: [],
        components: ["Muscle", "TimelineTrack", "ProgressTrack"],
        visual: "flow",
      },
    ],
  },
  {
    id: "kb_sweat_fat",
    slug: "sweat-is-not-fat",
    title: "Sweating is not fat loss",
    question: "Does sweating more mean you are burning more fat?",
    category: "myths",
    format: "myth",
    keywords: ["sweat", "thermoregulation", "fat oxidation", "sauna", "weight"],
    visual_score: 0.72,
    educational_score: 0.87,
    shareability: 0.92,
    hooks: [
      { type: "myth_buster", text: "MYTH: sweat is melted fat." },
      { type: "surprising_stat", text: "You can sweat in a cold room and stay in a freezer without losing fat." },
    ],
    arc: ["hook", "myth_card", "what_sweat_is", "why_it_exists", "what_is_lost", "weight_check", "payoff"],
    cta: "Sweat is thermoregulation. Fat loss comes from sustained energy balance.",
    source_card: ["Boron & Boulpaep — Medical Physiology", "ACSM position stand — Exercise and fluid replacement (2007)"],
    claims: [
      {
        id: "cl_swt_1",
        text: "Sweat is a salty fluid secreted to move heat away from the body when temperature rises.",
        level: "guideline",
        sources: ["acsM_exercise_fluid", "boron_medical_physiology"],
        permitted: ["is a salty fluid", "to move heat away", "thermoregulation"],
        forbidden: ["is melted fat", "is toxins leaving the body", "drains calories"],
        numbers: [],
        components: ["SkinDiagram", "ParticleFlow", "Counter"],
        visual: "diagram",
      },
      {
        id: "cl_swt_2",
        text: "Sweat rate varies with temperature, humidity, clothing and how accustomed you are, so it is not a measure of fat burned.",
        level: "guideline",
        sources: ["acsM_exercise_fluid"],
        permitted: ["varies with", "is not a measure of"],
        forbidden: ["measures fat loss exactly", "proves how hard you trained"],
        numbers: [],
        components: ["ComparisonBars", "LineChart"],
        visual: "comparison",
      },
      {
        id: "cl_swt_3",
        text: "Weight lost during a sweaty session is largely fluid, and is normally replaced by drinking.",
        level: "guideline",
        sources: ["acsM_exercise_fluid", "efsa_water"],
        permitted: ["is largely fluid", "is normally replaced"],
        forbidden: ["means you burned fat", "means you are dehydrated permanently"],
        numbers: [],
        components: ["Counter", "LineChart", "Kidney"],
        visual: "chart",
      },
    ],
  },
];

export const KB_TOPIC_BY_SLUG = new Map(KB_TOPICS.map((topic) => [topic.slug, topic]));
export const KB_TOPIC_BY_ID = new Map(KB_TOPICS.map((topic) => [topic.id, topic]));
